apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: calico-crd
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://jaciechao.github.io/charts/assets/rke2-calico-crd/rke2-calico-crd-v3.29.101.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: calico
  namespace: kube-system
spec:
  bootstrap: true
  chart: https://jaciechao.github.io/charts/assets/rke2-calico/rke2-calico-v3.29.200.tgz
  valuesContent: |-
    tigeraOperator:
      image: tigera/operator
      version: v1.36.5
    calicoctl:
      image: calico/ctl
      tag: v3.29.2
    ipamConfig:
      strictAffinity: true
      autoAllocateBlocks: true
    apiServer:
      enabled: false
    defaultFelixConfiguration: 
      enabled: false
    global:
      clusterCIDR: 10.42.0.0/16
      clusterCIDRv4: 10.42.0.0/16
      clusterDNS: 10.43.0.10
      clusterDomain: cluster.local
      rke2DataDir: /var/lib/rancher/rke2
      serviceCIDR: 10.43.0.0/16
    felixConfiguration:
      defaultEndpointToHostAction: Drop
      featureDetectOverride: ChecksumOffloadBroken=true
      healthPort: 9099
      logSeveritySys: Info
      wireguardEnabled: false
      xdpEnabled: true
    installation:
      controlPlaneTolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/etcd"
        operator: "Exists"
        effect: "NoExecute"
      enabled: true
      kubeletVolumePluginPath: None
      kubernetesProvider: "RKE2" 
      backend: VXLAN
      natOutgoing: Enabled
      calicoNetwork:
        bgp: Disabled
      imagePath: "calico"
      imagePrefix: ""
      flexVolumePath: /var/lib/kubelet/volumeplugins/
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
    kubeletVolumePluginPath: None
    kubernetesServiceEndpoint:
      host: ''
      port: '6443'
    tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
